FE 101 - Detail Page
lpzchrstn/FE-training pull request #2
Opened 2022-01-11 07:41 UTC by lpzchrstn

# Related Tickets

# Description
This PR has the default page structure and design of the Detail Page.

# Validation
No Validation yet for behavior, the page just needs to look like this site: https://www.christopher-ware.com/vsa

Here are some images related to this PR:
<img width="1680" alt="Screen Shot 2022-01-11 at 3 31 50 PM" src="https://user-images.githubusercontent.com/72726383/148900024-aa8a508c-5ef8-4223-b2c5-6a16945eb2ce.png">
<img width="1680" alt="Screen Shot 2022-01-11 at 3 32 24 PM" src="https://user-images.githubusercontent.com/72726383/148900044-56f9e60b-0b48-4437-9451-110bc9d3960c.png">
<img width="1680" alt="Screen Shot 2022-01-11 at 3 33 19 PM" src="https://user-images.githubusercontent.com/72726383/148900068-db85c774-8686-4f48-93ef-5ad9789846e6.png">

# Risks
This PR is using the compiled scripts and styles and can be generated by running  `npm start build`

2022-01-11 12:48 UTC, joshuacerbito requested changes
Left a few comments for you to address and consider, @lpzchrstn

2022-01-11 12:48 UTC, joshuacerbito commented on package.json
> +    "watching-js": "rollup -c ./src/config/rollup.config.js -w"
Please review the comment from https://github.com/lpzchrstn/sass-lpzchrstn/pull/1 as it's very much the same as this.

2022-01-11 12:48 UTC, joshuacerbito commented on .gitignore
> +dist/
Please make sure that there's always an empty line at the end of each file

2022-01-11 12:48 UTC, joshuacerbito commented on src/sass/main.scss
> +@import 'modules/fonts.scss';
Please make sure that there's always an empty line at the end of each file

2022-01-11 12:48 UTC, joshuacerbito commented on src/sass/modules/fonts.scss
> +}
Please make sure that there's always an empty line at the end of each file

2022-01-11 12:48 UTC, joshuacerbito commented on src/sass/modules/keyframes.scss
> +}
Please make sure that there's always an empty line at the end of each file

2022-01-12 02:34 UTC, lpzchrstn commented on package.json
> +    "watching-js": "rollup -c ./src/config/rollup.config.js -w"
Oh right, I just copied the package.json from that PR but forgot to update it.

2022-01-13 13:07 UTC, joshuacerbito approved these changes
All of these look good. For the next PRs, please make sure to always close the loop on the conversations.

2022-01-13 13:07 UTC, merged